name: laptopharbor
description: "E-Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.16
  get: ^4.6.6
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: 10.6.0
  animations: ^2.0.8
  image_picker: ^0.8.7+4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
